name: Binary Test

on: [push, pull_request]

jobs:
  run-binary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Make binary executable
      run: chmod +x ./bin/passgen_v1.1

    - name: Run tests on binary
      run: |
        ./bin/passgen_v1.1 --length 12
        ./bin/passgen_v1.1 --length 4 || echo "[OK] Detected invalid input"
