name: Binary Test

on: [push, pull_request]

jobs:
  run-binary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Make binary executable
      run: chmod +x ./bin/passgen_v.1.1

    - name: Run tests on binary
      run: |
        ./bin/passgen_v.1.1 -n 12 -l -d -s
        ./bin/passgen_v.1.1 -n 4 || echo "[OK] Detected invalid input"
